version: "3.9"

networks:
  msa-network:

services:
  UserService:
    build:
      context: ./UserService
    ports:
      - "${USER_SERVICE_PORT}:8085"
    environment:
      - SERVER_PORT=${USER_SERVICE_PORT}
    networks:
      - msa-network
  OrderService:
    build:
      context: ./OrderService
    ports:
      - "${ORDER_SERVICE_PORT}:8085"
    environment:
      - SERVER_PORT=${ORDER_SERVICE_PORT}
    networks:
      - msa-network
  ProductService:
    build:
      context: ./ProductService
    ports:
      - "${PRODUCT_SERVICE_PORT}:8085"
    environment:
      - SERVER_PORT=${PRODUCT_SERVICE_PORT}
    networks:
      - msa-network