version: "3.9"

networks:
  msa-network:

services:
  application:
    build:
      context: ./application
    ports:
      - "${APPLICATION_PORT}:8080"
    environment:
      - SERVER_PORT=${APPLICATION_PORT}
    networks:
      - msa-network
  domain:
    build:
      context: ./domain
    ports:
      - "${DOMAIN_PORT}:8080"
    environment:
      - SERVER_PORT=${DOMAIN_PORT}
    networks:
      - msa-network
  infrastructure:
    build:
      context: ./infrastructure
    ports:
      - "${INFRASTRUCTURE_PORT}:8080"
    environment:
      - SERVER_PORT=${INFRASTRUCTURE_PORT}
    networks:
      - msa-network
  webapi:
    build:
      context: ./webapi
    ports:
      - "${WEBAPI_PORT}:8080"
    environment:
      - SERVER_PORT=${WEBAPI_PORT}
    networks:
      - msa-network