version: "3.8"

networks:
  MSA:
    driver: bridge

services:
  eureka-server:
    build:
      context: ./EurekaServer
    container_name: eureka-server
    volumes:
      - ./EurekaServer/src/main:/app/src/main
      - ./EurekaServer/build/classes/java/main:/app/build/classes/java/main
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - MSA

  gateway:
    build:
      context: ./Gateway
    container_name: gateway
    volumes:
      - ./Gateway/src/main:/app/src/main
      - ./Gateway/build/classes/java/main:/app/build/classes/java/main
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8222:8222"
    depends_on:
      - eureka-server
    networks:
      - MSA

  order-service:
    build:
      context: ./OrderService
    container_name: order-service
    volumes:
      - ./OrderService/src/main:/app/src/main
      - ./OrderService/build/classes/java/main:/app/build/classes/java/main
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_DATASOURCE_URL=jdbc:mysql://db.cfu4cgmokcze.ap-northeast-2.rds.amazonaws.com:3306/OrderService
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - eureka-server
    networks:
      - MSA

  product-service:
    build:
      context: ./ProductService
    container_name: product-service
    volumes:
      - ./ProductService/src/main:/app/src/main
      - ./ProductService/build/classes/java/main:/app/build/classes/java/main
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8060:8060"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_DATASOURCE_URL=jdbc:mysql://db.cfu4cgmokcze.ap-northeast-2.rds.amazonaws.com:3306/ProductService
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - eureka-server
    networks:
      - MSA

  user-service:
    build:
      context: ./UserService
    container_name: user-service
    volumes:
      - ./UserService/src/main:/app/src/main
      - ./UserService/build/classes/java/main:/app/build/classes/java/main
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8050:8050"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_DATASOURCE_URL=jdbc:mysql://db.cfu4cgmokcze.ap-northeast-2.rds.amazonaws.com:3306/MemberService
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - eureka-server
    networks:
      - MSA

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - MSA