server:
  port: 8020
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: false
spring:
  application:
    name: PurchaseService
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: native
  main:
    web-application-type: reactive
    log-startup-info: true
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PURCHASE_SERVICE_DB_URL}
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true # IP ?? ???? ???? ??
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5000
    disable-delta: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    healthcheck:
      enabled: true # Health check ???
#logging:
#  level:
#    org.springframework.cloud: DEBUG