# spring.application.name=domain
spring:
  application:
    name: UserService
  profiles:
    active: native
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.cfu4cgmokcze.ap-northeast-2.rds.amazonaws.com:3306/FirstcomeFirstserve
    hikari:
      username: admin
      password: dlgudrn1998
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
application:
  config:
    webapi-url: http://localhost:8222/~
management:
  tracing:
    sampling:
      probability: 1.0