server:
  port: 8060
spring:
  application:
    name: ProductService
  profiles:
    active: native
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PURCHASE_SERVICE_DB_URL}
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  main:
    web-application-type: reactive
    log-startup-info: true
  cloud:
    compatibility-verifier:
      enabled: false
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5000
    disable-delta: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
logging:
  level:
    org.springframework.cloud: DEBUG