server:
  port: 8060
spring:
  application:
    name: ProductService
  profiles:
    active: native
  main:
    web-application-type: reactive
    log-startup-info: true
  cloud:
    config:
      uri: http://localhost:8888
    compatibility-verifier:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    appname: PRODUCTSERVICE
logging:
  level:
    org.springframework.cloud: DEBUG
