// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "[ Member ]회원가입 - 이메일인증",
    id: "76601222-a79f-40af-8317-5dbc40854bef",
    method: "POST",
    address: "http://localhost:8222/api/user/signup",
    data:
      '{\r\n  "userName": "홍길동",\r\n  "userEmail": "gildong@naver.com",\r\n  "userPw": "honggi12ldong!",\r\n  "userAddress": "지구어딘가",\r\n  "userPH": "010-1234-5678",\r\n  "profileImg": "",\r\n  "description": "안녕! 난 홍길동이라고 해!"\r\n}\r\n'
  });

  postman[Request]({
    name: "[ Member ] 로그인",
    id: "54617087-8b2b-40ff-85cc-4fb7dc000c5f",
    method: "POST",
    address: "http://localhost:8222/api/user/login",
    data:
      '{\r\n    "email" : "gildong@naver.com",\r\n    "password" : "honggi12ldong!"\r\n}',
    post(response) {
      const responseData = pm.response.json();
      pm.environment.set("token", responseData.token);
    }
  });

  postman[Request]({
    name: "[ Member ] 현재기기 로그아웃",
    id: "ffc1e444-ebac-4ed8-9a5e-e90ec77041d2",
    method: "POST",
    address: "http://localhost:8222/api/user/logout",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Member ] 전체기기 로그아웃",
    id: "f6afb0fa-cc09-49e0-a85d-25a866b9e724",
    method: "POST",
    address: "http://localhost:8222/api/user/logout/all",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Member ] 비밀번호 변경",
    id: "648f308f-16b1-4ca7-b9a3-c998a9466fc1",
    method: "PUT",
    address: "http://localhost:8222/api/user/password/change/request",
    data:
      '{\r\n    "email" : "gildong@naver.com",\r\n    "oldPassword" : "honggildong!",\r\n    "newPassword" : "ggggggg!",\r\n    "confirmPassword" : "ggggggg!"\r\n}',
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Product ] 상품 등록",
    id: "4349712e-b86a-4dbd-8b3d-caebae89b3a5",
    method: "PUT",
    address: "http://localhost:8222/api/product/register",
    data:
      '{\r\n    "productName" : "상품이름1",\r\n    "productDescription" : "상품설명1",\r\n    "productPrice" : 100,\r\n    "stockQuantity" : 1 \r\n}'
  });

  postman[Request]({
    name: "[ Product ] 상품 리스트 전체 조회",
    id: "93ba00f6-e2f5-4829-8ecb-04d5547c0f26",
    method: "GET",
    address: "http://localhost:8222/api/product/view/list"
  });

  postman[Request]({
    name: "[ Product ] 특정 상품 상세조회",
    id: "57b882c6-7f32-4ef5-950f-2f0be7637a9b",
    method: "GET",
    address:
      "http://localhost:8222/api/product/view?productName=%EC%83%81%ED%92%88%EC%9D%B4%EB%A6%841&productId="
  });

  postman[Request]({
    name: "[ Order ] 서버 테스트",
    id: "02192329-eb00-488f-9e07-c2d2666ca42f",
    method: "GET",
    address: "http://localhost:8222/api/order/test",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 주문 or 찜",
    id: "9401bb9b-f198-49b8-817c-ce3e616e0577",
    method: "POST",
    address: "http://localhost:8222/api/order/product/찜",
    data:
      '{\r\n    "productName" : "상품이름1",\r\n    "stockQuantity" : 1\r\n}',
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 주문 상태조회",
    id: "fb573510-083e-416d-83ad-7fa856bff6d2",
    method: "GET",
    address: "http://localhost:8222/api/order/view/order/status",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 주문 취소",
    id: "77689e3e-0ced-4b2f-ad83-c11c9aca40dc",
    method: "PUT",
    address: "http://localhost:8222/api/order/cancel/상품이름1",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 반품 신청",
    id: "69bf4140-0a29-4a6e-bb29-75cb347e5a16",
    method: "PUT",
    address: "http://localhost:8070/api/order/refund/상품이름1",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 위시리스트 및 주문내역 조회",
    id: "96c5428b-fed3-4748-91f1-3a3adb742fdb",
    method: "GET",
    address: "http://localhost:8222/api/order/mypage",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 위시리스트 조회",
    id: "a6c07e9f-f34a-4333-94e3-1929877d504b",
    method: "GET",
    address: "http://localhost:8222/api/order/wishlist",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 위시리스트에 있는 상품 주문",
    id: "7be9512c-4aa9-4f11-89be-dfb271079f3b",
    method: "POST",
    address: "http://localhost:8222/api/order/wishlist/order/13",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 위시리스트 상품 수량 조정",
    id: "db5df569-d267-4735-a99b-4dab3c58aa05",
    method: "PUT",
    address: "http://localhost:8222/api/order/wishlist/quantity/update/15",
    headers: {
      Authorization: "{{token}}"
    }
  });

  postman[Request]({
    name: "[ Order ] 위시리스트 상품 삭제",
    id: "f48aa474-4023-47c5-b6da-7b4560d6567e",
    method: "GET",
    address: "http://localhost:8222/api/order/wishlist/quantity/update/15"
  });
}
