// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import {sleep} from 'k6';

export let options = {maxRedirects: 4};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
    options
});
let token = "";

export default function () {
    postman[Request]({
        name: "[ Member ]회원가입 - 이메일인증",
        id: "c46261d4-a49d-4e26-9adf-0b640c1dc0fb",
        method: "POST",
        address: "http://localhost:8222/api/user/signup",
        headers: {
            "Content-Type": "application/json" // JSON 요청 헤더 추가
        },
        data: JSON.stringify({ // JSON 데이터 직렬화
            userName: "이형구",
            userEmail: "anrqlcdmlrja@naver.com",
            userPw: "glemfkafjl3ro!",
            userAddress: "지구어딘가",
            userPH: "010-1234-5678",
            profileImg: "",
            description: "안녕! 난 홍길동이라고 해!"
        })
    });
    sleep(1);

    postman[Request]({
        name: "[ Member ] 로그인",
        id: "6c968d10-119f-43c9-b93b-78e98547c724",
        method: "POST",
        address: "http://localhost:8222/api/user/login",
        headers: {
            "Content-Type": "application/json" // JSON 요청 헤더 설정
        },
        data: JSON.stringify({ // 요청 데이터를 JSON으로 직렬화
            email: "anrqlcdmlrja@naver.com",
            password: "glemfkafjl3ro!"
        }),
        post(response) {
            // console.log("Raw response:", JSON.stringify(response, null, 2)); // 응답 출력 (디버깅용)
            // 응답 본문에서 JSON 파싱
            const responseData = response.json();
            token = responseData.token; // 토큰 저장
        }
    });
    sleep(1);

    postman[Request]({
        name: "[ Member ] 현재기기 로그아웃",
        id: "a42ef25d-88ab-4546-95a5-743596a6e956",
        method: "POST",
        address: "http://localhost:8222/api/user/logout",
        headers: {
            Authorization: `${token}`
        }
    });
    // console.log(token)
    // if (!token) {
    //     console.error("토큰 값이 비어 있습니다. 로그인 요청이 실패했을 수 있습니다.");
    //     return;
    // }
    sleep(1);
    postman[Request]({
        name: "[ Member ] 전체기기 로그아웃",
        id: "6e736ff0-823f-4f1a-a641-45162eb1f2b2",
        method: "POST",
        address: "http://localhost:8222/api/user/logout/all",
        headers: {
            Authorization: `${token}`
        }

    });
    sleep(1);
    postman[Request]({
        name: "[ Member ] 비밀번호 변경",
        id: "1d8aa9d9-c758-4c55-a250-b167d1f33fb0",
        method: "PUT",
        address: "http://localhost:8222/api/user/password/change/request",
        data: JSON.stringify({
            email: "anrqlcdmlrja@naver.com",
            oldPassword: "glemfkajfl3ro!",
            newPassword: "ggggas123!",
            confirmPassword: "ggggas123!" // 서버와 필드 이름 일치
        }),
        headers: {
            "Content-Type": "application/json", // JSON 요청 헤더 추가
            Authorization: `${token}` // Bearer 토큰 형식
        }
    });

    sleep(1);
    postman[Request]({
        name: "[ Product ] 상품 등록",
        id: "98338485-d38e-41f7-b9ff-d88899de013d",
        method: "PUT",
        address: "http://localhost:8222/api/product/register",
        headers: {
            "Content-Type": "application/json" // JSON 요청 헤더 추가
        },
        data: JSON.stringify({ // JSON 데이터 직렬화
            productName: "상품이름1",
            productDescription: "상품설명1",
            productPrice: 100,
            stockQuantity: 3
        })
    });
    sleep(1);

    postman[Request]({
        name: "[ Product ] 상품 리스트 전체 조회",
        id: "e784e460-20a3-4c3a-9757-2f16ac225a7d",
        method: "GET",
        address: "http://localhost:8222/api/product/view/list"
    });
    sleep(1);
    let productName = encodeURIComponent("상품이름1");
    postman[Request]({

        name: "[ Product ] 특정 상품 상세조회",
        id: "883d52c7-b774-46ea-b71a-90277e32f18e",
        method: "GET",
        address:
            `http://localhost:8222/api/product/view?productName=${productName}&productId=1`
    });
    sleep(1);
    postman[Request]({
        name: "[ Order ] 서버 테스트",
        id: "2eb033ea-7f8c-4321-989c-c7502b1ea7e6",
        method: "GET",
        address: "http://localhost:8222/api/order/test",
        headers: {
            Authorization: `${token}`
        }
    });
    sleep(1);
    let order = encodeURIComponent("찜");

    postman[Request]({
        name: "[ Order ] 주문 or 찜",
        id: "b1435da4-94b9-4f62-9c30-287725226e6a",
        method: "POST",
        address: `http://localhost:8222/api/order/product/${order}`,
        headers: {
            "Content-Type": "application/json", // JSON 요청 헤더 추가
            Authorization: `${token}` // Bearer 형식으로 토큰 추가
        },
        data: JSON.stringify({ // JSON 데이터 직렬화
            productName: "상품이름1",
            stockQuantity: 1
        })
    });
    sleep(1);
    order = encodeURIComponent("주문");
    postman[Request]({
        name: "[ Order ] 주문 or 찜",
        id: "b1435da4-94b9-4f62-9c30-287725226e6a",
        method: "POST",
        address: `http://localhost:8222/api/order/product/${order}`,
        headers: {
            "Content-Type": "application/json", // JSON 요청 헤더 추가
            Authorization: `${token}` // Bearer 형식으로 토큰 추가
        },
        data: JSON.stringify({ // JSON 데이터 직렬화
            productName: "상품이름1",
            stockQuantity: 1
        })
    });
    sleep(1);
    postman[Request]({
        name: "[ Order ] 주문 or 찜",
        id: "b1435da4-94b9-4f62-9c30-287725226e6a",
        method: "POST",
        address: `http://localhost:8222/api/order/product/${order}`,
        headers: {
            "Content-Type": "application/json", // JSON 요청 헤더 추가
            Authorization: `${token}` // Bearer 형식으로 토큰 추가
        },
        data: JSON.stringify({ // JSON 데이터 직렬화
            productName: "상품이름1",
            stockQuantity: 1
        })
    });

    sleep(1);
    postman[Request]({
        name: "[ Order ] 주문 상태조회",
        id: "75164d93-1cd3-4d7f-88e7-58fd28232ab6",
        method: "GET",
        address: "http://localhost:8222/api/order/view/order/status",
        headers: {
            Authorization: `${token}`
        }
    });
    sleep(1);
    postman[Request]({
        name: "[ Order ] 주문 취소",
        id: "c156f312-a843-427b-b5c9-e266e0f6876b",
        method: "PUT",
        address: `http://localhost:8222/api/order/cancel/${productName}`,
        headers: {
            Authorization: `${token}`
        }
    });
    sleep(1);
    postman[Request]({
        name: "[ Order ] 반품 신청",
        id: "ac0dce26-97a8-467f-bbf4-6ad59f176e2a",
        method: "PUT",
        address: `http://localhost:8070/api/order/refund/${productName}`,
        headers: {
            Authorization: `${token}`
        }
    });
    sleep(1);
    postman[Request]({
        name: "[ Order ] 위시리스트 및 주문내역 조회",
        id: "96b5e0c9-5b15-4222-8752-4bdc608840d5",
        method: "GET",
        address: "http://localhost:8222/api/order/mypage",
        headers: {
            Authorization: `${token}`
        }
    });
    sleep(1);
    postman[Request]({
        name: "[ Order ] 위시리스트 조회",
        id: "24605807-a2b8-41fe-bafb-797e2822ebe2",
        method: "GET",
        address: "http://localhost:8222/api/order/wishlist",
        headers: {
            Authorization: `${token}`
        }
    });
    sleep(1);
    postman[Request]({
        name: "[ Order ] 위시리스트에 있는 상품 주문",
        id: "8e670569-a2db-492d-a57d-3032f107514c",
        method: "POST",
        address: "http://localhost:8222/api/order/wishlist/order/1",
        headers: {
            Authorization: `${token}`
        }
    });
    sleep(1);
    postman[Request]({
        name: "[ Order ] 위시리스트 상품 수량 조정",
        id: "ff13c251-001f-43f2-ad33-27c34585718f",
        method: "PUT",
        address: "http://localhost:8222/api/order/wishlist/quantity/update/1",
        headers: {
            "Content-Type": "application/json", // JSON 요청 헤더 추가
            Authorization: `${token}` // Bearer 토큰 형식으로 수정
        },
        data: JSON.stringify({ // JSON 데이터 직렬화
            quantity: 5 // 수량 업데이트 값
        })
    });
    sleep(1);

    postman[Request]({
        name: "[ Order ] 위시리스트 상품 삭제",
        id: "6a986b7c-5645-4ee7-9a3a-81c4bbda1eda",
        method: "GET",
        address: "http://localhost:8222/api/order/wishlist/quantity/update/1"
    });
}
