server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
spring:
  application:
    name: Gateway
  jackson:
    time-zone: Asia/Seoul
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - name: JwtAuthenticationFilter
      routes:
        - id: UserService
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/user/**
        - id: ProductService
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/api/product/**
        - id: OrderService
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/api/order/**
        - id: PurchaseService
          uri: lb://PURCHASESERVICE
          predicates:
            - Path=/api/purchase/**

management:
  tracing:
    enabled: false

logging:
  level:
    org.springframework.security.web.csrf: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

jwt:
  secret: ${SECRET_KEY}
