server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: Gateway
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: UserService
#          uri: lb://USERSERVICE
          uri: http://user-service:8050
          predicates:
            - Path=/api/user/**
        - id: ProductService
#          uri: lb://PRODUCTSERVICE
          uri: http://product-service:8060
          predicates:
            - Path=/api/product/**
        - id: OrderService
#          uri: lb://ORDERSERVICE
          uri: http://order-service:8070
          predicates:
            - Path=/api/order/**

management:
  tracing:
    enabled: false