server:
  port: 8050
# spring.application.name=UserService
spring:
  application:
    name: UserService
  profiles:
    active: reactive
  r2dbc:
    url: r2dbc:mysql://db.cfu4cgmokcze.ap-northeast-2.rds.amazonaws.com:3306/MemberService
    username: admin
    password: dlgudrn1998
    pool:
      enabled: true
      initial-size: 10
      max-size: 300
  sql:
    init:
      schema-locations: classpath:schema.sql
      platform: mysql
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
  main:
    web-application-type: reactive
    log-startup-info: true
  cloud:
    compatibility-verifier:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: dpfmzlskwpf@gmail.com
    password: gojz trfn nsfp gqis
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5000
    disable-delta: true
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      exampleService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      exampleService:
        maxAttempts: 3
        waitDuration: 2s

management:
  tracing:
    enabled: false
jwt:
  secret: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUU=
#  secret: ${SECRET_KEY}
logging:
  level:
    org.springframework: info
    io.r2dbc: info
