# spring.application.name=OrderService
server:
  port: 8070
spring:
  application:
    name: OrderService
  profiles:
    active: native
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.cfu4cgmokcze.ap-northeast-2.rds.amazonaws.com:3306/OrderService
    hikari:
      username: admin
      password: dlgudrn1998
  main:
    web-application-type: reactive
    log-startup-info: true
  cloud:
    compatibility-verifier:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5000
    disable-delta: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    enabled: false
jwt:
  secret: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUU=
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud: DEBUG