apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30001
  type: NodePort
