spring:
  config:
    import: optional:configserver:http://localhost:8888 # Config Server URL
  application:
    name: webapi
  datasource:
    url: jdbc:mysql://db.cfu4cgmokcze.ap-northeast-2.rds.amazonaws.com:3306/FirstcomeFirstserve
    username: admin
    password: dlgudrn1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    web-application-type: reactive
    log-startup-info: true
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: dpfmzlskwpf@gmail.com
    password: gojz trfn nsfp gqis
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8084